### ISSUE TITLE
Inconsistent type display

### ISSUE THREAD

**Issue by Ingo60** [Frege/try-frege#17]
When the repl can't print a result it prints its type at least, which is a good thing.
However, the type differs from the one shown with `:t`

For example:

    frege> (println (), println ())
    :: (ST RealWorld (),ST RealWorld ())
    frege> :t (println (), println ())
    (IO (),IO ())

Just checked the 3.22.367 command-line REPL, and it does it consistently.

**Comment by mmhelloworld** [comment]
This is fixed now and the online REPL is updated.

**Comment by Ingo60** [comment]
Hmmm ... not for me. Will it take some time to populate to good ole europe?
