### ISSUE TITLE
Comment in refers to vehicles which were removed from code in the editor

### ISSUE THREAD

**Issue by ml10** [Frege/try-frege#20]
The comments in index.html refer to a variable that is no longer supplied by the code in the editor:
> ...or type some expression like 'take 2 vehicles'

The examples no longer provide a vehicles value to play with, so this errors out when you try it in the REPL.

The new example doesn't really provide an option for using similar functions out of the box, so I'm not sure if some new example code should be added or just this snippet removed.

**Comment by mmhelloworld** [comment]
Thanks for pointing that out! The comment should be updated to reflect the
code. I will fix it.
